spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect